name: Metrics

on:
  # Schedule hourly update
  schedule: [{cron: "0 * * * *"}]

  workflow_dispatch:
  push: 
    branches: [master]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mkflan
          template: classic
          config_timezone: America/Chicago
          base: header, activity, community
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_notable: yes
          plugin_notable_types: issue, pull_request, commit
          plugin_languages: yes
          plugin_languages_categories: programming
